baseURL = "http://example.com/"
languageCode = "en-us"
title = "C.Smith's Blog"
theme = "minimal"


[params]
    author = "Chris Smith"
    description = "Quick R Tutorials"
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2


# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:chrissmith700@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/csmith6"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/c_smizzle?lang=en"
    name = "twitter"
    weight = 3

